import puppeteer from 'puppeteer-core';
const CHROME = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const browser = await puppeteer.launch({ executablePath: CHROME, headless: 'new', args: ['--no-sandbox'] });
const p = await browser.newPage(); await p.setViewport({width:1280,height:900,deviceScaleFactor:1.5});
await p.goto('http://localhost:4321/',{waitUntil:'domcontentloaded'});
await p.waitForSelector('input[type="text"]',{timeout:15000});
await p.type('input[type="text"]','demo'); await p.type('input[type="password"]','calvinball123');
await p.click('button[type="submit"]'); await p.waitForSelector('.persona-pill',{timeout:20000});
await p.evaluate(()=>window.switchPersona('dp')); await new Promise(r=>setTimeout(r,400));
await p.evaluate(()=>window.openCell('dp-scorecard')); await new Promise(r=>setTimeout(r,1000));
const ok = await p.evaluate(()=>({kpis:!!document.getElementById('dpgKpis')?.innerText, rail:!!document.querySelector('.kj-rail')}));
console.log('modal check:', JSON.stringify(ok));
await p.screenshot({path:'/tmp/rd-modal.png'});
await browser.close(); console.log('done');
